### ISSUE TITLE
Issue on connect

### ISSUE THREAD

**Issue by BertDuyck** [wo6zz/fs-gdrive#1]
When I call GDrive.connect() an error is thrown that there is no fileId provided.
This makes no sense as I only try to connect. I dont need any files at this stage.

```
const fsGDrive = new GDrive({
        folderId: 'MY_FOLDER_ID_I_WANT_TO_ACCESS',
        auth: {
            email: '*** my mail',
            privateKey: "*** my key",
        },
    });


async function connectGDrive(fsGDrive){
    return await fsGDrive.connect();
}
```

```
(node:25816) UnhandledPromiseRejectionWarning: Error: Failed to connect to Google Drive: Missing required parameters: fileId
    at GDrive.connect (H:\development\electron-quick-start\node_modules\fs-gdrive\dist\index.cjs:104977:19)
    at async connectGDrive (H:\development\electron-quick-start\electron\main.js:123:12)
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:25816) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2) 
```

**Comment by wo6zz** [comment]
Sorry for late response _(didn't get notification from github tbh)_,

if you are using `v1.3.0` the param `folderId` got renamed to "[root](https://github.com/wo6zz/fs-gdrive/blob/da48dbbb5ccb75d0533f7985eb251f213882b5ff/src/typings/interface.ts#L13)"
